name: api_caller
description: A flexible API helper built on Dio with support for
  singleton usage, dynamic base URL override, per-request bearer token,
  JSON & FormData requests, and typed responses.

version: 2.0.1

homepage: https://github.com/infyrise
repository: https://github.com/infyrise/api_caller
issue_tracker: https://github.com/infyrise/api_caller/issues

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  dio: ^5.9.0

dev_dependencies:
  test: ^1.28.0
  mockito: ^5.5.0
  build_runner: ^2.4.0
  lints: ^2.0.0
platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:



topics:
  - api
  - dio
  - http
  - network
  - dart

screenshots:
  - description: Simple API requests with Dio and typed responses
    path: assets/api_helper_example.png
