name: api_helper
description: Api Helper based on Dio
version: 1.0.5
repository: https://github.com/iemektar/api_helper

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  custom_response: ^1.0.3
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
