name: api_caller
description: A lightweight helper for making HTTP API calls using Dart.
version: 1.0.6

repository: https://github.com/infyrise
homepage: https://github.com/infyrise/api_helper
issue_tracker: https://github.com/infyrise/api_helper/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
